CREATE TABLE Company (
  ID   NUMERIC      NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);
INSERT INTO Company(ID,TITLE)VALUES (1,'Sber');
INSERT INTO Company(ID,TITLE)VALUES (2,'GazProm');

CREATE TABLE Account (
  ID   NUMERIC      NOT NULL,
  OWNERID NUMERIC   NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  RATE DOUBLE       NOT NULL,
  PRIMARY KEY (ID)
);
INSERT INTO Account(ID, OWNERID, NAME, RATE) VALUES (1,1,'Ivan123',2.0);
INSERT INTO Account(ID, OWNERID, NAME, RATE) VALUES (2,1,'Ivan007',1.0);
INSERT INTO Account(ID, OWNERID, NAME, RATE) VALUES (3,2,'Bob1980',2.5);

CREATE TABLE Owner (
  ID   NUMERIC      NOT NULL,
  COMPANYID NUMERIC   NOT NULL,
  FIRSTNAME VARCHAR(255) NOT NULL,
  SECONDNAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO Owner(ID, COMPANYID, FIRSTNAME, SECONDNAME) VALUES (1,1,'Ivan','Ivanov');
INSERT INTO Owner(ID, COMPANYID, FIRSTNAME, SECONDNAME) VALUES (2,2,'Bob','Bobrov');